### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by ChouYuFuck** [LSPosed/MagiskOnWSA#148] opened 2021-12-21 09:07 UTC
![QQ截图20211221170413](https://user-images.githubusercontent.com/84790055/146902508-a1f441b6-ed14-44e6-b43a-c49170d60277.jpg)

**Comment by yujincheng08** [comment] 2021-12-21 09:09
0x80073cf9

Duplicate of #107 #125 #38

**Closed by yujincheng08** 2021-12-21 09:09 UTC
