### ISSUE TITLE
Run workflow error

### ISSUE THREAD

**Issue by MisakaOne** [LSPosed/MagiskOnWSA#474] opened 2022-07-20 14:18 UTC
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f[80](https://github.com/MisakaOne/MagiskOnWSA/runs/7431085213?check_suite_focus=true#step:3:81)1a9ab280>: Failed to establish a new connection: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='store.rg-adguard.net', port=443): Max retries exceeded with url: /api/GetFiles (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f801a9ab280>: Failed to establish a new connection: [Errno 111] Connection refused'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/runner/work/_temp/07a7d96a-614a-4fa2-b7c6-6736a675373f.py", line 12, in <module>
    res = requests.post("https://store.rg-adguard.net/api/GetFiles", f"type=CategoryId&url=[85](https://github.com/MisakaOne/MagiskOnWSA/runs/7431085213?check_suite_focus=true#step:3:86)8014f3-3[93](https://github.com/MisakaOne/MagiskOnWSA/runs/7431085213?check_suite_focus=true#step:3:94)4-4abe-8078-4aa193e74ca8&ring={release_type}&lang=en-US", headers={
  File "/usr/lib/python3/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='store.rg-adguard.net', port=443): Max retries exceeded with url: /api/GetFiles (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f801a9ab280>: Failed to establish a new connection: [Errno [111](https://github.com/MisakaOne/MagiskOnWSA/runs/7431085213?check_suite_focus=true#step:3:112)] Connection refused'))
Error: Process completed with exit code 1.

**Comment by OgnistyPoland** [comment] 2022-07-20 14:33
Same problem. Tried 10 times

**Comment by yujincheng08** [comment] 2022-07-20 14:48
Duplicate of #473

**Closed by yujincheng08** 2022-07-20 14:48 UTC
Labels: duplicate
