### ISSUE TITLE
wsa auto closing 

### ISSUE THREAD

**Issue by vignakke** [LSPosed/MagiskOnWSA#102] opened 2021-11-22 20:56 UTC
my wsa stopping working after running good for a week, i tried to uninstall / reinstall (normal wsa and gapps version) 6-7 times but it always do this: https://streamable.com/9ss9ss

**Comment by tfragment** [comment] 2021-11-23 04:09
I think the cause is the OS. You're using a custom OS right? Because I'm the same here using :Censored:. and the thing just won't run. But still... idk.

**Comment by yujincheng08** [comment] 2021-11-23 08:15
Check if there's any log in `%LOCALAPPDATA%\Packages\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\LocalState\diagnostics\logcat`. If so, send the latest log so that I can check it for you.

**Comment by vignakke** [comment] 2021-11-23 08:44
> I think the cause is the OS. You're using a custom OS right? Because I'm the same here using :Censored:. and the thing just won't run. But still... idk.

hey, yes actualy using custom os but this os support wsa (wsa running great like 5-6 days) but stopped working after my computer got bsod when im using wsa

**Comment by vignakke** [comment] 2021-11-23 08:45
> %LOCALAPPDATA%\Packages\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\LocalState\diagnostics\logcat

hey, all logs are 0kb 
![image](https://user-images.githubusercontent.com/69920044/142993732-07dcb8d2-f993-4634-b11d-e9dbdd68daa2.png)

**Comment by vignakke** [comment] 2021-11-23 09:17
another find: 
![image](https://user-images.githubusercontent.com/69920044/142998130-d851fd54-b29c-441a-b09c-3442443e10c2.png)

`Faulting application name: WsaClient.exe, version: 1.8.32828.0, time stamp: 0x6194010d
Faulting module name: ucrtbase.dll, version: 10.0.22000.1, time stamp: 0x00e78ce9
Exception code: 0xc0000409
Fault offset: 0x000000000007dd7e
Faulting process id: 0x3750
Faulting application start time: 0x01d7e04a620593cf
Faulting application path: C:\Users\Administrator\Downloads\WSA-with-magisk-GApps-nano_1.8.32828.0_x64_Release-Nightly\WsaClient\WsaClient.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: 6bd9c9fb-6db5-408e-b89d-5a234c465524
Faulting package full name: MicrosoftCorporationII.WindowsSubsystemForAndroid_1.8.32828.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App`

**Comment by vignakke** [comment] 2021-11-23 13:51
fixed: reinstall windows with usb...

**Comment by vignakke** [comment] 2021-11-26 10:10
finaly not ... @yujincheng08 here a file log 
[25112021213116.log](https://github.com/LSPosed/MagiskOnWSA/files/7607987/25112021213116.log)

**Comment by vignakke** [comment] 2021-11-26 10:13
> finaly not ... @yujincheng08 here a file log [25112021213116.log](https://github.com/LSPosed/MagiskOnWSA/files/7607987/25112021213116.log)

https://wormhole.app/k9jWm#cWFcoEpHkwPFwAuYpPi46Q (second text file but like 37mb)

**Comment by yujincheng08** [comment] 2021-11-26 14:53
Found something useful
```
java.lang.RuntimeException: Unable to create application com.google.android.setupwizard.SetupWizardApplication
```

What variant of GApps you are using?

**Comment by vignakke** [comment] 2021-11-26 14:55
nano

**Comment by yujincheng08** [comment] 2021-11-26 14:57
Could you please try to append ` --exclude='setupwizarddefault-x86_64'` to this line (need extra space):
https://github.com/LSPosed/MagiskOnWSA/blob/16ecbee62ccd1349fce5fe97b5d0646619df5bb3/.github/workflows/magisk.yml#L143

**Comment by vignakke** [comment] 2021-11-26 15:02
uhm i dont know how

**Comment by yujincheng08** [comment] 2021-11-26 15:07
Never mid, try this build: https://github.com/LSPosed/MagiskOnWSA/actions/runs/1508047292

**Comment by yujincheng08** [comment] 2021-11-26 15:15
It seems that this is not a good idea to remove it

**Comment by vignakke** [comment] 2021-11-26 15:17
working !!!  ty bro
![image](https://user-images.githubusercontent.com/69920044/143601700-f3bb792a-a324-43de-915a-b32ab672fd0a.png)

**Comment by yujincheng08** [comment] 2021-11-26 15:18
I will dig into it more and please help me do more test

**Comment by vignakke** [comment] 2021-11-26 15:36
ok

**Comment by yujincheng08** [comment] 2021-11-26 15:49
Ok, I think we cannot solve it without modifying opengapps. It should be fixed by opengapps I suppose.

**Closed by yujincheng08** 2021-11-26 15:49 UTC

**Comment by yujincheng08** [comment] 2021-11-26 16:13
I open an issue in OpenGApps and hopes it can be fixed: opengapps/opengapps#945

**Comment by yujincheng08** [comment] 2021-11-29 03:37
@vignakke Hi, could you try if this build works? https://github.com/LSPosed/MagiskOnWSA/actions/runs/1514337126

**Comment by vignakke** [comment] 2021-11-29 09:07
> @vignakke Hi, could you try if this build works? https://github.com/LSPosed/MagiskOnWSA/actions/runs/1514337126

hey, actually downloading this build update you in 30m-1hours

**Comment by vignakke** [comment] 2021-11-29 09:34
seem to work for the moment will post log file if crashes again
